### ISSUE TITLE
Instance system.adapter.squeezeboxrpc.1 terminated with code 6 (UNCAUGHT_EXCEPTION)

### ISSUE THREAD

**Issue by cyberius0** [oweitman/ioBroker.squeezeboxrpc#71] opened 2023-03-10 21:54 UTC
**Describe the bug**  
I have set up two piCorePlayer devices for my children. 
This adapter works with one of them without any problem. But with the other LMS device, this adapter crashes. It crashes every time directly after starting so that after some time iobroker stops starting it.
Both piCorePlayers were set up at the same time so they should behave nearly the same... But they contain different songs and playlists.

This is the log output:

```
host.smarthome | 2023-03-10 22:45:13.558 | error | instance system.adapter.squeezeboxrpc.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
squeezeboxrpc.1 | 2023-03-10 22:45:12.952 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
squeezeboxrpc.1 | 2023-03-10 22:45:12.951 | info | terminating
squeezeboxrpc.1 | 2023-03-10 22:45:12.950 | info | squeezeboxrpc unloaded
squeezeboxrpc.1 | 2023-03-10 22:45:12.938 | error | Cannot read properties of undefined (reading 'hasOwnProperty')
squeezeboxrpc.1 | 2023-03-10 22:45:12.938 | error | TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')     at ioSBPlayer.doPlayerUpdateStatus (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbplayer.js:547:28)     at IoSbServer.<anonymous> (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbserver.js:659:31)     at handle (/opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:62:13)     at /opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:164:13     at ClientHttp.Client._parseResponse (/opt/iobroker/node_modules/jayson/lib/client/index.js:219:10)     at /opt/iobroker/node_modules/jayson/lib/client/index.js:150:10     at Object.Utils.JSON.parse (/opt/iobroker/node_modules/jayson/lib/utils.js:266:3)     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/jayson/lib/client/http.js:86:22)     at IncomingMessage.emit (node:events:525:35)     at endReadableNT (node:internal/streams/readable:1358:12)
squeezeboxrpc.1 | 2023-03-10 22:45:12.934 | error | uncaught exception: Cannot read properties of undefined (reading 'hasOwnProperty')
```

**Versions:**  
 - Adapter version: v1.3.10
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: Raspberry Debian Bullseye

**Comment by oweitman** [comment] 2023-03-10 21:57
I will check it

**Comment by cyberius0** [comment] 2023-03-10 22:15
Thank you!
Here's some more information about those two piCorePlayers (both same versions):
```
Logitech Media Server Version: 8.1.1 - 1610364019 @ Thu Jan 14 06:27:45 CET 2021
piCorePlayer v8.1.0 | www v00017 | linux 5.10.77-pcpCore-v7 (32) | piCore v13.1 | Squeezelite v1.9.9-1403-pCP
```

And here's silly debug output:
```

host.smarthome | 2023-03-10 23:13:59.889 | warn | Do not restart adapter system.adapter.squeezeboxrpc.1 because restart loop detected
-- | -- | -- | --
host.smarthome | 2023-03-10 23:13:59.889 | info | Restart adapter system.adapter.squeezeboxrpc.1 because enabled
host.smarthome | 2023-03-10 23:13:59.889 | error | instance system.adapter.squeezeboxrpc.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
squeezeboxrpc.1 | 2023-03-10 23:13:59.304 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
squeezeboxrpc.1 | 2023-03-10 23:13:59.303 | info | terminating
squeezeboxrpc.1 | 2023-03-10 23:13:59.302 | info | squeezeboxrpc unloaded
squeezeboxrpc.1 | 2023-03-10 23:13:59.291 | error | Cannot read properties of undefined (reading 'hasOwnProperty')
squeezeboxrpc.1 | 2023-03-10 23:13:59.290 | error | TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')     at ioSBPlayer.doPlayerUpdateStatus (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbplayer.js:547:28)     at IoSbServer.<anonymous> (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/lib/iosbserver.js:659:31)     at handle (/opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:62:13)     at /opt/iobroker/node_modules/squeezenode-oweitman/squeezerequest.js:164:13     at ClientHttp.Client._parseResponse (/opt/iobroker/node_modules/jayson/lib/client/index.js:219:10)     at /opt/iobroker/node_modules/jayson/lib/client/index.js:150:10     at Object.Utils.JSON.parse (/opt/iobroker/node_modules/jayson/lib/utils.js:266:3)     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/jayson/lib/client/http.js:86:22)     at IncomingMessage.emit (node:events:525:35)     at endReadableNT (node:internal/streams/readable:1358:12)
squeezeboxrpc.1 | 2023-03-10 23:13:59.288 | error | uncaught exception: Cannot read properties of undefined (reading 'hasOwnProperty')
squeezeboxrpc.1 | 2023-03-10 23:13:58.290 | debug | New Player found: piCorePlayerTom with id b1:22:ab:14:c8:b1
squeezeboxrpc.1 | 2023-03-10 23:13:58.289 | debug | createObject btnRewind
squeezeboxrpc.1 | 2023-03-10 23:13:58.289 | debug | createObject btnPreset_6
squeezeboxrpc.1 | 2023-03-10 23:13:58.289 | debug | createObject btnPreset_5
squeezeboxrpc.1 | 2023-03-10 23:13:58.288 | debug | createObject btnPreset_4
squeezeboxrpc.1 | 2023-03-10 23:13:58.288 | debug | createObject btnPreset_3
squeezeboxrpc.1 | 2023-03-10 23:13:58.288 | debug | createObject btnPreset_2
squeezeboxrpc.1 | 2023-03-10 23:13:58.287 | debug | createObject btnPreset_1
squeezeboxrpc.1 | 2023-03-10 23:13:58.287 | debug | createObject btnForward
squeezeboxrpc.1 | 2023-03-10 23:13:58.287 | debug | createObject cmdGoTime
squeezeboxrpc.1 | 2023-03-10 23:13:58.286 | debug | createObject cmdGeneral
squeezeboxrpc.1 | 2023-03-10 23:13:58.285 | debug | createObject cmdPlayUrl
squeezeboxrpc.1 | 2023-03-10 23:13:58.285 | debug | createObject cmdPlayFavorite
squeezeboxrpc.1 | 2023-03-10 23:13:58.285 | debug | createObject RadioName
squeezeboxrpc.1 | 2023-03-10 23:13:58.284 | debug | createObject Url
squeezeboxrpc.1 | 2023-03-10 23:13:58.284 | debug | createObject Artist
squeezeboxrpc.1 | 2023-03-10 23:13:58.284 | debug | createObject Title
squeezeboxrpc.1 | 2023-03-10 23:13:58.284 | debug | createObject Type
squeezeboxrpc.1 | 2023-03-10 23:13:58.283 | debug | createObject Genre
squeezeboxrpc.1 | 2023-03-10 23:13:58.283 | debug | createObject Album
squeezeboxrpc.1 | 2023-03-10 23:13:58.283 | debug | createObject Bitrate
squeezeboxrpc.1 | 2023-03-10 23:13:58.282 | debug | createObject ArtworkUrl
squeezeboxrpc.1 | 2023-03-10 23:13:58.282 | debug | createObject Duration
squeezeboxrpc.1 | 2023-03-10 23:13:58.282 | debug | createObject state
squeezeboxrpc.1 | 2023-03-10 23:13:58.281 | debug | createObject Alarms
squeezeboxrpc.1 | 2023-03-10 23:13:58.281 | debug | createObject PlaylistCurrentIndex
squeezeboxrpc.1 | 2023-03-10 23:13:58.281 | debug | createObject Playlist
squeezeboxrpc.1 | 2023-03-10 23:13:58.281 | debug | createObject Remote
squeezeboxrpc.1 | 2023-03-10 23:13:58.280 | debug | createObject PlaylistShuffle
squeezeboxrpc.1 | 2023-03-10 23:13:58.280 | debug | createObject PlaylistRepeat
squeezeboxrpc.1 | 2023-03-10 23:13:58.280 | debug | createObject Volume
squeezeboxrpc.1 | 2023-03-10 23:13:58.279 | debug | createObject SyncMaster
squeezeboxrpc.1 | 2023-03-10 23:13:58.278 | debug | createObject SyncSlaves
squeezeboxrpc.1 | 2023-03-10 23:13:58.278 | debug | createObject Rate
squeezeboxrpc.1 | 2023-03-10 23:13:58.278 | debug | createObject Time
squeezeboxrpc.1 | 2023-03-10 23:13:58.278 | debug | createObject Mode
squeezeboxrpc.1 | 2023-03-10 23:13:58.277 | debug | createObject Power
squeezeboxrpc.1 | 2023-03-10 23:13:58.277 | debug | createObject IP
squeezeboxrpc.1 | 2023-03-10 23:13:58.276 | debug | createObject Connected
squeezeboxrpc.1 | 2023-03-10 23:13:58.276 | debug | createObject PlayerID
squeezeboxrpc.1 | 2023-03-10 23:13:58.276 | debug | createObject Playername
squeezeboxrpc.1 | 2023-03-10 23:13:58.270 | debug | createObject Server.SyncGroups
squeezeboxrpc.1 | 2023-03-10 23:13:58.270 | debug | createObject Server.getFavorites
squeezeboxrpc.1 | 2023-03-10 23:13:58.269 | debug | createObject Server.PlayerCountOther
squeezeboxrpc.1 | 2023-03-10 23:13:58.269 | debug | createObject Server.PlayerCount
squeezeboxrpc.1 | 2023-03-10 23:13:58.268 | debug | createObject Server.TotalDuration
squeezeboxrpc.1 | 2023-03-10 23:13:58.268 | debug | createObject Server.TotalSongs
squeezeboxrpc.1 | 2023-03-10 23:13:58.267 | debug | createObject Server.TotalGenres
squeezeboxrpc.1 | 2023-03-10 23:13:58.266 | debug | createObject Server.TotalArtists
squeezeboxrpc.1 | 2023-03-10 23:13:58.266 | debug | createObject Server.TotalAlbums
squeezeboxrpc.1 | 2023-03-10 23:13:58.266 | debug | createObject Server.mac
squeezeboxrpc.1 | 2023-03-10 23:13:58.265 | debug | createObject Server.uuid
squeezeboxrpc.1 | 2023-03-10 23:13:58.264 | debug | createObject Server.Version
squeezeboxrpc.1 | 2023-03-10 23:13:58.263 | debug | createObject Server.LastScan
squeezeboxrpc.1 | 2023-03-10 23:13:58.252 | debug | All favorite objects deleted
squeezeboxrpc.1 | 2023-03-10 23:13:58.095 | info | starting.  Version 1.3.10 (non-npm: oweitman/ioBroker.squeezeboxrpc) in  /opt/iobroker/node_modules/iobroker.squeezeboxrpc, node: v16.19.1,  js-controller: 4.0.24
host.smarthome | 2023-03-10 23:13:55.842 | info | instance system.adapter.squeezeboxrpc.1 started with pid 8131

```

**Comment by MAR-L3Y** [comment] 2023-03-18 02:00
Hello,

i got the same issue with the adapter crashing and getting recognized as in bootloop state.
The Errorcode is exactly the same @cyberius0 got in the posted log. 

- Iobroker Docker (Unraid)
- JS-Controller version: 4.0.24
- Node version: v16.19.0
- Adapter version: v1.3.10

**Comment by oweitman** [comment] 2023-03-20 14:12
the issue is (hopefully) fixed on my development system.
for another issue actually i have to think about the solution.
after that ist fixed, i will release a new update, but first only on github
an hope that you will test this release.

this issue i can't reproduce it on my system, because this variable is never empty. 
but i implement a sanity check that the program will fallback and dont crash.

**Comment by cyberius0** [comment] 2023-04-21 23:23
> the issue is (hopefully) fixed on my development system. for another issue actually i have to think about the solution. after that ist fixed, i will release a new update, but first only on github and hope that you (and some others) will test this release.
> 
> this issue i can't reproduce it on my system, because this variable is never empty. but i implement a sanity check that the program will fallback and dont crash.

Hello,
could you upload your fix please, so we can test it?

Thank you

**Comment by MAR-L3Y** [comment] 2023-05-14 08:17
> the issue is (hopefully) fixed on my development system. for another issue actually i have to think about the solution. after that ist fixed, i will release a new update, but first only on github and hope that you (and some others) will test this release.
> 
> this issue i can't reproduce it on my system, because this variable is never empty. but i implement a sanity check that the program will fallback and dont crash.

Can you estimate when we could test the adapter with fallback function?

**Comment by Arekmaster** [comment] 2023-11-14 20:41
Hi @oweitman,
the same problem is to me. Is there already a solution for this?

I'm using:

RPi4 
js-controller: 5.0.16
Adapter Version: 1.3.10

Thanks

**Comment by MAR-L3Y** [comment] 2023-11-14 21:14
> Hi @oweitman, the same problem is to me. Is there already a solution for this?
> 
> I'm using:
> 
> RPi4 js-controller: 5.0.16 Adapter Version: 1.3.10
> 
> Thanks

i use a workaround at the moment, because there was no reply for 5 month so i needed an alternative. My workaround is a http request i send with blockly. I use this to start the playback or stop the playback. i think there are quite more possibilities with that. if you want  to use that as well pls send me a message and i'll try to share my research for the commands for http requests with you.

**Comment by Arekmaster** [comment] 2023-11-14 22:34
I have just installed a new Logitech Media Server on my PC and iOBroker as well, just for testing purposes. At the beginning it worked perfectly. After playing around a bit, I got the same behavior as on my other setup.

This made me a bit suspicious and so I did some more research and was able to solve the problem. 

In the past, I activated the UPnP/DLNA Bridge and connected my Samsung TV via it. The new LMS was then able to add this TV to the newly installed server and that's when the problems started. Now that I have removed the TV (I don't need it), everything is green again and works perfectly. 

Maybe this will help some others to solve the problem.

**Comment by oweitman** [comment] 2023-11-23 22:51
sorry, i try to push my dev repository to github on sunday.
sorry again for the delay, actualy there are some other projects that i have focused

**Comment by MAR-L3Y** [comment] 2023-11-23 22:55
no problem, take your time. if you release your dev repo to github we habe to install it over the github link in iobroker to get the newest version to test - is that correct?

**Comment by oweitman** [comment] 2023-11-23 23:00
yes,
iobroker -> adapter with expert mode -> octocat button ->on dialog octocat tab-> type adapter name

**Comment by oweitman** [comment] 2023-11-26 20:24
ok, please check

**Comment by MAR-L3Y** [comment] 2023-11-26 20:50
> ok, please check

The version stays 1.3.10 is that correct?
it seems you fixed the problem with the title not showing correctly i mentioned in the other post is that also correct?

sofar this thing is runnig again. if there are any problems i'll let you know.
thanks for your work.

**Comment by oweitman** [comment] 2023-11-27 09:13
if i push the adapter to npm then a new version will be created

**Comment by oweitman** [comment] 2024-08-05 02:17
v1.3.11 is now available in the beta repository

**Closed by oweitman** 2024-08-05 02:17 UTC
